replicaCount: 1

metadata:
 name: angular 
 label: angular

hpa:
  metadata:
    name: frontend-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 50
    resource:
      name: cpu
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: angular

image:
  name: angular
  imageName: "icpdevcluster.icp:8500/default/angular:latest" 
  imagePullPolicy: Always

service:
  serviceMetadata:
    name: angular
  selector:
    selectorName: angular
  servicePortConfiguration:
    name: angular
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30080