# The IBM version of this configuration
version : 0.0.3

container-name-run : "listing-mongo-microservice-run"


host-path-run : .
host-path-tools : .

dockerfile-run : "Dockerfile"

image-name-run : "listing-mongo-microservice-run"

chart-path: "chart/listing-mongo-microservice"
deploy-target: "container"
deploy-image-target: "mycluster.icp:8500/default/listing-mongo-microservice"