apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: signupsvcmicroservicehpa
spec:
  maxReplicas: 5
  minReplicas: 1                      
  metrics:    
  # - type: Pods
  #   pods:
  #     metricName: memory_usage_bytes
  #     targetAverageValue: 10485760                        
  - type: Resource
    resource:                              
      name: cpu                          
      targetAverageUtilization: 3     
  scaleTargetRef:                          
    apiVersion: extensions/v1beta1         
    kind: Deployment                       
    name: signupsvc