apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: bookingsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: bookingsvc
     labels:
       app: bookingsvc
   spec:
     containers:
       - name: bookingsvc
         image: "mycluster.icp:8500/default/booking-microservice:latest" 
         imagePullPolicy: Always
         resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "128Mi"
         env:
          - name: UID
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: UID
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PASSWORD
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SECRET
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: NODE_ENV
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: DATABASE
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: PORT
          - name: HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: HOSTNAME
          - name: PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: PROTOCOL
         ports:
         - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 name: bookingsvc
 labels:
   app: bookingsvc
spec:
 type: NodePort
 selector:
   app: bookingsvc
 ports:
  - protocol: TCP
    name: bookingsvc
    port: 3000
    targetPort: 3000
    nodePort: 30090
