replicaCount: 1

metadata:
 name: ethereumsvc 
 label: ethereumsvc

image:
  name: ethereumsvc
  imageName: "icpdevcluster.icp:8500/default/ethereum-microservice:latest" 
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 3000
  requests:
    cpu: "250m"
    memory: "64Mi"
  limit:
    cpu: "1"
    memory: "128Mi"
    
envOfSecrets:
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envHttpProvider:
    name: HttpProvider
    configMapKeyRef:
      name: env-database
      key: HttpProvider
  envCONTRACTADRESS:
    name: CONTRACTADRESS
    configMapKeyRef:
      name: env-database
      key: CONTRACTADRESS
  envETHEREUMACCOUNT:
    name: ETHEREUMACCOUNT
    configMapKeyRef:
      name: env-database
      key: ETHEREUMACCOUNT

service:
  serviceMetadata:
    name: ethereumsvc
    labels:
      app: ethereumsvc
  selector:
    selectorName: ethereumsvc
  servicePortConfiguration:
    protocol: TCP
    name: ethereumsvc
    type: NodePort
    port: 3008
    targetPort: 3008
    nodePort: 30089