apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: emailsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: emailsvc
     labels:
       app: emailsvc
   spec:
     containers:
       - name: emailsvc
         image: "mycluster.icp:8500/default/email-microservice:latest" 
         imagePullPolicy: Always
         resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "128Mi"
         env:
          - name: EMAILUSERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: EMAILUSERNAME
          - name: EMAILPASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: EMAILPASSWORD

         ports:
         - containerPort: 3006
---
apiVersion: v1
kind: Service
metadata:
 name: emailsvc
 labels:
   app: emailsvc
spec:
 type: NodePort
 selector:
   app: emailsvc
 ports:
  - protocol: TCP
    name: emailsvc
    port: 3006
    targetPort: 3006
    nodePort: 30199
