apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: authservicecronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: cron
              image: "mycluster.icp:8500/icp-airways/cron:0.0.1" 
          restartPolicy: Never
          terminationGracePeriodSeconds: 30