apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: authservicecronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: cron
              image: "mycluster.icp:8500/icp-airways/cron:0.0.1" 
              args:
                - /bin/sh
                - -ec
                - siege -c 50 -r 10 -b http://loginsvc.icp-airways:3003/healthz
          restartPolicy: Never
          terminationGracePeriodSeconds: 30