replicaCount: 1

metadata:
 name: bookingsvc 
 label: bookingsvc

readinessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 15

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 5
  timeoutSeconds: 1 
  periodSeconds: 15

hpa:
  metadata:
    name: booking-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 80 
    memory:
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: bookingsvc


image:
  name: bookingsvc
  imageName: "icpdevcluster.icp:8500/default/booking-microservice:latest" 
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 3000
  requests:
    cpu: "100m"
    memory: "30Mi"
  limits:
    cpu: "110m"
    memory: "361Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
    
envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: mysecret
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: mysecret
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: env-database
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: env-database
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: env-database
      key: PORT
  envHOSTNAME:
    name: HOSTNAME
    configMapKeyRef:
      name: env-database
      key: HOSTNAME
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: env-database
      key: PROTOCOL

ingress:
  metadeta:
    name: bookingsvc
  path: /bookingsvc
  serviceName: bookingsvc
  servicePort: 3000

service:
  serviceMetadata:
    name: bookingsvc
    labels:
      app: bookingsvc
  selector:
    selectorName: bookingsvc
  servicePortConfiguration:
    protocol: TCP
    name: bookingsvc
    type: NodePort
    port: 3000
    targetPort: 3000

serviceMonitor:
  metadata:
    name: serviceMonitorBookingsvc
    labels:
      app: serviceMonitorBookingsvc
  specs: 
    selector:
      matchLabels:
        app: serviceMonitorBookingsvc
    port: bookingsvc