replicaCount: 1

metadata:
 name: signupsvc 
 label: signupsvc

readinessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10

livenessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 10
  timeoutSeconds: 2 
  periodSeconds: 10

image:
  name: signupsvc
  imageName: "mycluster.icp:8500/default/signup-microservice:0.0.1" 
  imagePullPolicy: Always
  ports:
    containerPort: 3004
  requests:
    cpu: "100m"
    memory: "30Mi"
  limits:
    cpu: "110m"
    memory: "361Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
  
ingress:
  name: signupsvc
  path: /signupsvc
  serviceName: signupsvc
  servicePort: 3004

envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: mysecret
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: mysecret
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: env-database
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: env-database
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: env-database
      key: PORT
  envHOSTNAME:
    name: HOSTNAME
    configMapKeyRef:
      name: env-database
      key: HOSTNAME
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: env-database
      key: PROTOCOL

hpa:
  metadata:
    name: signupsvcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 1
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
  scaleTargetRef:  
    name: signupsvc

service:
  serviceMetadata:
    name: signupsvc
    labels:
      app: signupsvc
  selector:
    selectorName: signupsvc
  servicePortConfiguration:
    protocol: TCP
    name: signupsvc
    type: NodePort
    port: 3004
    targetPort: 3004


serviceMonitor:
  metadata:
    name: servicemonitorsignupsvc
    labels:
      app: servicemonitorsignupsvc
  specs: 
    selector:
      matchLabels:
        app: servicemonitorsignupsvc
    port: signupsvc