replicaCount: 1

metadata:
 name: bookingsvc 
 label: bookingsvc

readinessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10

hpa:
  metadata:
    name: bookingmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 1
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: bookingsvc


image:
  name: bookingsvc
  imageName: "mycluster.icp.icp:8500/default/booking-microservice:0.0.1" 
  imagePullPolicy: Always
  ports:
    containerPort: 3000
  requests:
    cpu: "50m"
    memory: "150Mi"
  limits:
    cpu: "80m"
    memory: "200Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
    
envOfSecrets:
  envUID:
    name: MARIADBUID
    secretKeyRef:
      name: mysecret
      key: MARIADBUID
  envPASSWORD:
    name: MARIADBPASSWORD
    secretKeyRef:
      name: mysecret
      key: MARIADBPASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envDATABASE:
    name: MARIADBDATABASE
    configMapKeyRef:
      name: env-database
      key: MARIADBDATABASE
  envPORT:
    name: MARIADBPORT
    configMapKeyRef:
      name: env-database
      key: MARIADBPORT
  envHOSTNAME:
    name: MARIADBHOSTNAME
    configMapKeyRef:
      name: env-database
      key: MARIADBHOSTNAME
  envPROTOCOL:
    name: MARIADBPROTOCOL
    configMapKeyRef:
      name: env-database
      key: MARIADBPROTOCOL


service:
  serviceMetadata:
    name: bookingsvc
    labels:
      app: bookingsvc
  selector:
    selectorName: bookingsvc
  servicePortConfiguration:
    protocol: TCP
    name: bookingsvc
    type: NodePort
    port: 3000
    targetPort: 3000
