# The IBM version of this configuration
version : 0.0.3

container-name-run : "checkin-microservice-run"


host-path-run : .
host-path-tools : .

dockerfile-run : "Dockerfile"

image-name-run : "checkin-microservice-run"

chart-path: "chart/checkin-microservice"
deploy-target: "container"
deploy-image-target: "mycluster.icp:8500/default/checkin-microservice:0.0.1"