apiVersion: v1
kind: Service
metadata:
  name: mapsvc
  labels:
    app: mapsvc
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: mapsvc
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mapsvc
spec:
  gateways:
  - mesh
  hosts:
  - 'mapsvc.default.svc.cluster.local'
  http:
  - match:
    - uri:
        prefix: /mapsvc/
    rewrite:
      uri: "/"
      authority: mapsvc.svc.b.remote
    route:
    - destination:
        host: ingress.b.remote
        port:
          number: 80
      weight: 100