replicaCount: 3

metadata:
 name: emailsvc 
 label: emailsvc
readinessProbe:
  path: /healthz
  port: 3006
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 15

livenessProbe:
  path: /healthz
  port: 3006
  initialDelaySeconds: 5
  timeoutSeconds: 1 
  periodSeconds: 15

hpa:
  metadata:
    name: email-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 80 
    memory:
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: emailsvc

image:
  name: emailsvc
  imageName: "icpdevcluster.icp:8500/default/email-microservice:0.0.1" 
  imagePullPolicy: Always
  ports:
    containerPort: 3006
  requests:
    cpu: "50m"
    memory: "30Mi"
  limits:
    cpu: "100m"
    memory: "35Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]

envOfSecrets:
  envEMAILPASSWORD:
    name: EMAILPASSWORD
    secretKeyRef:
      name: mysecret
      key: EMAILPASSWORD

envOfConfigmaps:
  envEMAILUSERNAME:
    name: EMAILUSERNAME
    configMapKeyRef:
      name: env-database
      key: EMAILUSERNAME

ingress:
  metadeta:
    name: emailsvc
  path: /emailsvc
  serviceName: emailsvc
  servicePort: 3006

service:
  serviceMetadata:
    name: emailsvc
    labels:
      app: emailsvc
  selector:
    selectorName: emailsvc
  servicePortConfiguration:
    protocol: TCP
    name: emailsvc
    type: NodePort
    port: 3006
    targetPort: 3006

serviceMonitor:
  metadata:
    name: serviceMonitorEmailsvc
    labels:
      app: serviceMonitorEmailsvc
  specs: 
    selector:
      matchLabels:
        app: serviceMonitorEmailsvc
    port: emailsvc