replicaCount: 1

metadata:
 name: bookingsvc 
 label: bookingsvc

hpa:
  metadata:
    name: booking-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 80 
    memory:
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: bookingsvc


image:
  name: bookingsvc
  imageName: "icpdevcluster.icp:8500/default/booking-microservice:latest" 
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 3000
  requests:
    cpu: "250m"
    memory: "64Mi"
  limit:
    cpu: "1"
    memory: "128Mi"
  maxSurge: 2
  maxUnavailable: 0
    
envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: mysecret
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: mysecret
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: env-database
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: env-database
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: env-database
      key: PORT
  envHOSTNAME:
    name: HOSTNAME
    configMapKeyRef:
      name: env-database
      key: HOSTNAME
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: env-database
      key: PROTOCOL

ingress:
  metadeta:
    name: bookingsvc
  path: /bookingsvc
  serviceName: bookingsvc
  servicePort: 3000

service:
  serviceMetadata:
    name: bookingsvc
    labels:
      app: bookingsvc
  selector:
    selectorName: bookingsvc
  servicePortConfiguration:
    protocol: TCP
    name: bookingsvc
    type: NodePort
    port: 3000
    targetPort: 3000