apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: listingsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: listingsvc
     labels:
       app: listingsvc
   spec:
     containers:
       - name: listingsvcluster
         image: "mycluster.icp:8500/default/listing-microservice:latest" 
         imagePullPolicy: Always
         resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "128Mi"
         env:
          - name: UID
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: UID
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PASSWORD
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SECRET
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: NODE_ENV
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: DATABASE
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: PORT
          - name: HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: HOSTNAME
          - name: PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: PROTOCOL
         ports:
         - containerPort: 3002
        #  livenessProbe:
        #     httpGet:
        #       path: /healthz
        #       port: 8080
        #       scheme: HTTP
        #     initialDelaySeconds: 30
        #     periodSeconds: 30
        #  readinessProbe:
        #     httpGet:
        #       path: /readiness
        #       port: 8080
        #       scheme: HTTP
        #     initialDelaySeconds: 30
        #     periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
 name: listingsvc
 labels:
   app: listingsvc
spec:
 type: NodePort
 selector:
   app: listingsvc
 ports:
  - protocol: TCP
    name: listingsvc
    port: 3002  
    targetPort: 3002 
    nodePort: 30092
