replicaCount: 1

metadata:
 name: listingsvc 
 label: listingsvc

image:
  name: listingsvc
  imageName: "icpdevcluster.icp:8500/default/listing-microservice:latest" 
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 3002
  requests:
    cpu: "250m"
    memory: "64Mi"
  limit:
    cpu: "1"
    memory: "128Mi"
  maxSurge: 2
  maxUnavailable: 0
envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: mysecret
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: mysecret
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

ingress:
  metadeta:
    name: listingsvc
  path: /listingsvc
  serviceName: listingsvc
  servicePort: 3002

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: env-database
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: env-database
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: env-database
      key: PORT
  envHOSTNAME:
    name: HOSTNAME
    configMapKeyRef:
      name: env-database
      key: HOSTNAME
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: env-database
      key: PROTOCOL

hpa:
  metadata:
    name: listingsvc-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 80 
    memory:
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: listingsvc

service:
  serviceMetadata:
    name: listingsvc
    labels:
      app: listingsvc
  selector:
    selectorName: listingsvc
  servicePortConfiguration:
    protocol: TCP
    name: listingsvc
    type: NodePort
    port: 3002
    targetPort: 3002
