apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: listingsvc-poolejector
  namespace: default
spec:
  destination:
    namespace: default
    name: listingsvc
    labels:
      app: listingsvc
  loadBalancing:
    name: RANDOM
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 1
      sleepWindow: 15s
      httpDetectionInterval: 5s
      httpMaxEjectionPercent: 100
---
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: emailsvc-poolejector
  namespace: default
spec:
  destination:
    namespace: default
    name: emailsvc
    labels:
      app: emailsvc
  loadBalancing:
    name: RANDOM
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 1
      sleepWindow: 15s
      httpDetectionInterval: 5s
      httpMaxEjectionPercent: 100
---
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: loginsvc-poolejector
  namespace: default
spec:
  destination:
    namespace: default
    name: loginsvc
    labels:
      app: loginsvc
  loadBalancing:
    name: RANDOM
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 1
      sleepWindow: 15s
      httpDetectionInterval: 5s
      httpMaxEjectionPercent: 100
---
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: bookingsvc-poolejector
  namespace: default
spec:
  destination:
    namespace: default
    name: bookingsvc
    labels:
      app: bookingsvc
  loadBalancing:
    name: RANDOM
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 1
      sleepWindow: 15s
      httpDetectionInterval: 5s
      httpMaxEjectionPercent: 100