apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: listingsvc-retry
spec:
  destination:
    namespace: default
    name: listingsvc
  route:
  - labels:
      app: listingsvc
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 2s
      attempts: 3
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: emailsvc-retry
spec:
  destination:
    namespace: default
    name: emailsvc
  route:
  - labels:
      app: emailsvc
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 2s
      attempts: 3
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: loginsvc-retry
spec:
  destination:
    namespace: default
    name: loginsvc
  route:
  - labels:
      app: loginsvc
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 2s
      attempts: 3
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: bookingsvc-retry
spec:
  destination:
    namespace: default
    name: bookingsvc
  route:
  - labels:
      app: bookingsvc
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 2s
      attempts: 3