replicaCount: 3

metadata:
 name: odmsvc 
 label: odmsvc

readinessProbe:
  path: /healthz
  port: 3005
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 15

livenessProbe:
  path: /healthz
  port: 3005
  initialDelaySeconds: 5
  timeoutSeconds: 1 
  periodSeconds: 15
image:
  name: odmsvc
  imageName: "icpdevcluster.icp:8500/default/odm-microservice:latest" 
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 3005
  requests:
    cpu: "50m"
    memory: "30Mi"
  limits:
    cpu: "100m"
    memory: "35Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
hpa:
  metadata:
    name: odmsvc-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 80 
    memory:
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: odmsvc

envOfSecrets:
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envODM:
    name: ODM
    configMapKeyRef:
      name: env-database
      key: ODM

ingress:
  metadeta:
    name: odmsvc
  path: /odmsvc
  serviceName: odmsvc
  servicePort: 3005

service:
  serviceMetadata:
    name: odmsvc
    labels:
      app: odmsvc
  selector:
    selectorName: odmsvc
  servicePortConfiguration:
    protocol: TCP
    name: odmsvc
    type: NodePort
    port: 3005
    targetPort: 3005

  
serviceMonitor:
  metadata:
    name: serviceMonitorOdmsvc
    labels:
      app: serviceMonitorOdmsvc
  specs: 
    selector:
      matchLabels:
        app: serviceMonitorOdmsvc
    port: odmsvc