apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: listingsvc
spec:
  gateways:
  - ingress-gateway
  - mesh
  hosts:
  - listingsvc.svc.b.remote
  http:
  - route:
    - destination:
        host: listingsvc
        port:
          number: 80
      weight: 100