apiVersion: v1
kind: ConfigMap
metadata:
  name: env-database
  namespace: default
data:
  NODE_ENV: development
  DATABASE: SAMPLE
  PORT: '50000'
  HOSTNAME: 'saqrairway-ibm-db2oltp-dev-db2.default'
  PROTOCOL: TCPIP
  ODM: 'http://169.61.62.89:32473/DecisionService/rest/FlightBooking/FlightPricing'
  CELERY_RESULT_BACKEND: 'amqp://admin:admin@10.150.20.151:30554'
  CELERY_BROKER_URL: 'amqp://admin:admin@10.150.20.151:30554'
  EMAILAPI: 'http://emailsvc.default:3006/email'
  MONGOPORT: '27017'