replicaCount: 3

metadata:
 name: emailsvc 
 label: emailsvc


hpa:
  metadata:
    name: email-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 80 
    memory:
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: emailsvc

image:
  name: emailsvc
  imageName: "icpdevcluster.icp:8500/default/email-microservice:latest" 
  imagePullPolicy: Always
  ports:
    containerPort: 3006
  requests:
    cpu: "250m"
    memory: "64Mi"
  limit:
    cpu: "1"
    memory: "128Mi"
  maxSurge: 2
  maxUnavailable: 0 
envOfSecrets:
  envEMAILPASSWORD:
    name: EMAILPASSWORD
    secretKeyRef:
      name: mysecret
      key: EMAILPASSWORD

envOfConfigmaps:
  envEMAILUSERNAME:
    name: EMAILUSERNAME
    configMapKeyRef:
      name: env-database
      key: EMAILUSERNAME

ingress:
  metadeta:
    name: emailsvc
  path: /emailsvc
  serviceName: emailsvc
  servicePort: 3006

service:
  serviceMetadata:
    name: emailsvc
    labels:
      app: emailsvc
  selector:
    selectorName: emailsvc
  servicePortConfiguration:
    protocol: TCP
    name: emailsvc
    type: NodePort
    port: 3006
    targetPort: 3006

serviceMonitor:
  metadata:
    name: serviceMonitorEmailsvc
    labels:
      app: serviceMonitorEmailsvc
  specs: 
    selector:
      matchLabels:
        app: serviceMonitorEmailsvc
    port: emailsvc