replicaCount: 1

metadata:
 name: signupsvc 
 label: signupsvc

readinessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 15

livenessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 5
  timeoutSeconds: 1 
  periodSeconds: 15

image:
  name: signupsvc
  
  imageName: "icpdevcluster.icp:8500/default/signup-microservice:latest" 
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 3004
  requests:
    cpu: "250m"
    memory: "64Mi"
  limit:
    cpu: "1"
    memory: "128Mi"
  maxSurge: 2
  maxUnavailable: 0
  
ingress:
  metadeta:
    name: signupsvc
  path: /signupsvc
  serviceName: signupsvc
  servicePort: 3004

envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: mysecret
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: mysecret
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: env-database
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: env-database
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: env-database
      key: PORT
  envHOSTNAME:
    name: HOSTNAME
    configMapKeyRef:
      name: env-database
      key: HOSTNAME
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: env-database
      key: PROTOCOL

hpa:
  metadata:
    name: signupsvc-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 80 
    memory:
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: signupsvc

service:
  serviceMetadata:
    name: signupsvc
    labels:
      app: signupsvc
  selector:
    selectorName: signupsvc
  servicePortConfiguration:
    protocol: TCP
    name: signupsvc
    type: NodePort
    port: 3004
    targetPort: 3004


serviceMonitor:
  metadata:
    name: serviceMonitorSignupsvc
    labels:
      app: serviceMonitorSignupsvc
  specs: 
    selector:
      matchLabels:
        app: serviceMonitorSignupsvc
    port: signupsvc