replicaCount: 1

metadata:
 name: loginsvc 
 label: loginsvc
readinessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 15

livenessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 5
  timeoutSeconds: 1 
  periodSeconds: 15
image:
  name: loginsvc
  imageName: "icpdevcluster.icp:8500/default/login-microservice:latest" 
  imagePullPolicy: Always
  ports:
    containerPort: 3003
  requests:
    cpu: "100m"
    memory: "30Mi"
  limits:
    cpu: "110m"
    memory: "361Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
  
hpa:
  metadata:
    name: loginsvc-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 80 
    memory:
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: loginsvc

envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: mysecret
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: mysecret
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: env-database
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: env-database
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: env-database
      key: PORT
  envHOSTNAME:
    name: HOSTNAME
    configMapKeyRef:
      name: env-database
      key: HOSTNAME
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: env-database
      key: PROTOCOL

ingress:
  metadeta:
    name: loginsvc
  path: /loginsvc
  serviceName: loginsvc
  servicePort: 3003

service:
  serviceMetadata:
    name: loginsvc
    labels:
      app: loginsvc
  selector:
    selectorName: loginsvc
  servicePortConfiguration:
    protocol: TCP
    name: loginsvc
    type: NodePort
    port: 3003
    targetPort: 3003

serviceMonitor:
  metadata:
    name: serviceMonitorLoginsvc
    labels:
      app: serviceMonitorLoginsvc
  specs: 
    selector:
      matchLabels:
        app: serviceMonitorLoginsvc
    port: loginsvc