replicaCount: 3

metadata:
 name: odmsvc 
 label: odmsvc

image:
  name: odmsvc
  imageName: "icpdevcluster.icp:8500/default/odm-microservice:latest" 
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 3005
  maxSurge: 2
  maxUnavailable: 0
  requests:
    cpu: "250m"
    memory: "64Mi"
  limit:
    cpu: "1"
    memory: "128Mi"

hpa:
  metadata:
    name: odmsvc-microservice-HPA
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 80 
    memory:
      targetAverageUtilization: 80 
  scaleTargetRef:  
    name: odmsvc

envOfSecrets:
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envODM:
    name: ODM
    configMapKeyRef:
      name: env-database
      key: ODM

ingress:
  metadeta:
    name: odmsvc
  path: /odmsvc
  serviceName: odmsvc
  servicePort: 3005

service:
  serviceMetadata:
    name: odmsvc
    labels:
      app: odmsvc
  selector:
    selectorName: odmsvc
  servicePortConfiguration:
    protocol: TCP
    name: odmsvc
    type: NodePort
    port: 3005
    targetPort: 3005