apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: saqrairwayingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - secretName: foo-secret
  rules:
   - http:
      paths:
      - path: /listingsvc
        backend:
          serviceName: listingsvc
          servicePort: 7000
      - path: /rabbitmq
        backend:
          serviceName: rabbitmq-ibm-rabbitmq-dev
          servicePort: 5672