replicaCount: 1

metadata:
 name: emailsvc 
 label: emailsvc
readinessProbe:
  path: /healthz
  port: 3006
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 15

livenessProbe:
  path: /healthz
  port: 3006
  initialDelaySeconds: 5
  timeoutSeconds: 1 
  periodSeconds: 15

hpa:
  metadata:
    name: emailmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 1
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: emailsvc

image:
  name: emailsvc
  imageName: "mycluster.icp:8500/default/email-microservice:0.0.1" 
  imagePullPolicy: Always
  ports:
    containerPort: 3006
  requests:
    cpu: "60m"
    memory: "150Mi"
  limits:
    cpu: "80m"
    memory: "200Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]

envOfSecrets:
  envEMAILPASSWORD:
    name: EMAILPASSWORD
    secretKeyRef:
      name: mysecret
      key: EMAILPASSWORD
  envEMAILUSERNAME:
    name: EMAILUSERNAME
    configMapKeyRef:
      name: mysecret
      key: EMAILUSERNAME


ingress:
  metadeta:
    name: emailsvc
  path: /emailsvc
  serviceName: emailsvc
  servicePort: 3006

service:
  serviceMetadata:
    name: emailsvc
    labels:
      app: emailsvc
  selector:
    selectorName: emailsvc
  servicePortConfiguration:
    protocol: TCP
    name: emailsvc
    type: ClusterIP
    port: 3006
    targetPort: 3006

serviceMonitor:
  metadata:
    name: serviceMonitorEmailsvc
    labels:
      app: serviceMonitorEmailsvc
  specs: 
    selector:
      matchLabels:
        app: serviceMonitorEmailsvc
    port: emailsvc